/**
 * Piano dei conti WEISS v4 con centri di costo.
 *
 * Fonte: docs/Piano_dei_conti_gestionale_WEISS_v4.xlsx, foglio "Piano dei
 * conti" (righe 2-156) e foglio "Centri di costo". Trascrizione verbatim:
 * nomi, note e ordinamento seguono l'Excel senza correzioni ortografiche o
 * riformulazioni. Vedi anche il foglio "Legenda" per i criteri di codifica.
 *
 * Struttura del codice a tre livelli: MASTRO (2 cifre) . GRUPPO (1 cifra,
 * solo dove il mastro è articolato) . VOCE (2 cifre). I movimenti si
 * registrano sempre sulla voce di dettaglio; mastro e gruppo sono livelli di
 * aggregazione per la lettura.
 *
 * regolaCentro: 'OBBLIGATORIO' = il gestionale deve rifiutare la
 * registrazione senza centro di costo. 'DEFAULT_STR' = se il centro non
 * viene indicato, il movimento va automaticamente sul centro Struttura/
 * Amministrazione (STR).
 */

export type RegolaCentro = 'OBBLIGATORIO' | 'DEFAULT_STR'

export interface VocePianoV4 {
  code: string // "20.1.01"
  nome: string
  tipo: 'RICAVO' | 'COSTO'
  mastroCode: string // "20"
  mastroNome: string // "Materie prime, sussidiarie e merci"
  gruppoCode?: string // "20.1" — presente solo nei mastri 20, 28, 32
  gruppoNome?: string // "Beverage alcolico"
  regolaCentro: RegolaCentro
  nota?: string // colonna G dell'Excel, se presente
}

export const PIANO_CONTI_WEISS_V4: readonly VocePianoV4[] = [
  // ─── RICAVI ───────────────────────────────────────────────────────────
  {
    code: '10.01',
    nome: 'Corrispettivi',
    tipo: 'RICAVO',
    mastroCode: '10',
    mastroNome: 'Ricavi delle vendite e delle prestazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '10.09',
    nome: 'Resi, sconti e abbuoni su vendite',
    tipo: 'RICAVO',
    mastroCode: '10',
    mastroNome: 'Ricavi delle vendite e delle prestazioni',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Segno negativo: rettifica dei ricavi',
  },
  {
    code: '11.01',
    nome: 'Ricavi eventi serali (ingressi e consumazioni)',
    tipo: 'RICAVO',
    mastroCode: '11',
    mastroNome: 'Ricavi eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '11.02',
    nome: 'Ricavi eventi privati e compleanni',
    tipo: 'RICAVO',
    mastroCode: '11',
    mastroNome: 'Ricavi eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '12.01',
    nome: 'Proventi vari',
    tipo: 'RICAVO',
    mastroCode: '12',
    mastroNome: 'Altri ricavi e proventi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '12.02',
    nome: 'Contributi in conto esercizio',
    tipo: 'RICAVO',
    mastroCode: '12',
    mastroNome: 'Altri ricavi e proventi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '12.03',
    nome: 'Rimborsi assicurativi',
    tipo: 'RICAVO',
    mastroCode: '12',
    mastroNome: 'Altri ricavi e proventi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '12.04',
    nome: 'Premi, bonus e contributi da fornitori',
    tipo: 'RICAVO',
    mastroCode: '12',
    mastroNome: 'Altri ricavi e proventi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '12.06',
    nome: 'Sopravvenienze attive',
    tipo: 'RICAVO',
    mastroCode: '12',
    mastroNome: 'Altri ricavi e proventi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '12.07',
    nome: 'Plusvalenze da alienazione cespiti',
    tipo: 'RICAVO',
    mastroCode: '12',
    mastroNome: 'Altri ricavi e proventi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '13.01',
    nome: 'Interessi attivi bancari',
    tipo: 'RICAVO',
    mastroCode: '13',
    mastroNome: 'Proventi finanziari',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '13.02',
    nome: 'Altri proventi finanziari',
    tipo: 'RICAVO',
    mastroCode: '13',
    mastroNome: 'Proventi finanziari',
    regolaCentro: 'DEFAULT_STR',
  },

  // ─── COSTI ────────────────────────────────────────────────────────────
  // 20 - Materie prime, sussidiarie e merci
  {
    code: '20.1.01',
    nome: 'Birra fusto',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.1',
    gruppoNome: 'Beverage alcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.1.02',
    nome: 'Birra bottiglia e lattina',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.1',
    gruppoNome: 'Beverage alcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.1.03',
    nome: 'Distillati e liquori',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.1',
    gruppoNome: 'Beverage alcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.1.04',
    nome: 'Vermouth, bitter e aperitivi',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.1',
    gruppoNome: 'Beverage alcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.1.05',
    nome: 'Vini',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.1',
    gruppoNome: 'Beverage alcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.2.01',
    nome: 'Bibite e soft drink',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.2',
    gruppoNome: 'Beverage analcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.2.02',
    nome: 'Acqua minerale',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.2',
    gruppoNome: 'Beverage analcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.2.03',
    nome: 'Succhi, nettari e centrifugati',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.2',
    gruppoNome: 'Beverage analcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.2.04',
    nome: 'Sciroppi, purea e mixer',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.2',
    gruppoNome: 'Beverage analcolico',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.3.01',
    nome: 'Caffè',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.3',
    gruppoNome: 'Caffetteria',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.3.02',
    nome: 'Latte e derivati',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.3',
    gruppoNome: 'Caffetteria',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.3.03',
    nome: 'Tè, infusi e cioccolata',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.3',
    gruppoNome: 'Caffetteria',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.3.04',
    nome: 'Zucchero e complementi caffetteria',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.3',
    gruppoNome: 'Caffetteria',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.4.01',
    nome: 'Beni alimentari e gastronomia',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.4',
    gruppoNome: 'Food',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.4.02',
    nome: 'Frutta e verdura',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.4',
    gruppoNome: 'Food',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.4.03',
    nome: 'Pane e prodotti da forno',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.4',
    gruppoNome: 'Food',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.4.04',
    nome: 'Pasticceria e dolci',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.4',
    gruppoNome: 'Food',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.4.05',
    nome: 'Snack e prodotti confezionati',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.4',
    gruppoNome: 'Food',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.5.01',
    nome: 'Ghiaccio',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.5',
    gruppoNome: 'Consumabili di servizio',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.5.02',
    nome: 'Garnish e decorazioni',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.5',
    gruppoNome: 'Consumabili di servizio',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.5.03',
    nome: 'Monouso, packaging e asporto',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.5',
    gruppoNome: 'Consumabili di servizio',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.5.04',
    nome: 'Materiale igiene e pulizia',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.5',
    gruppoNome: 'Consumabili di servizio',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.5.05',
    nome: 'Altri materiali di consumo',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.5',
    gruppoNome: 'Consumabili di servizio',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.6.01',
    nome: 'Resi, sconti e premi su acquisti',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.6',
    gruppoNome: 'Rettifiche e variazioni',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Segno negativo: rettifica dei costi',
  },
  {
    code: '20.6.02',
    nome: 'Rimanenze iniziali',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.6',
    gruppoNome: 'Rettifiche e variazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.6.03',
    nome: 'Rimanenze finali',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.6',
    gruppoNome: 'Rettifiche e variazioni',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Segno negativo: riduce il consumo',
  },
  {
    code: '20.6.04',
    nome: 'Ammanchi, rotture e cali',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.6',
    gruppoNome: 'Rettifiche e variazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '20.6.05',
    nome: 'Omaggi, autoconsumo e staff meal',
    tipo: 'COSTO',
    mastroCode: '20',
    mastroNome: 'Materie prime, sussidiarie e merci',
    gruppoCode: '20.6',
    gruppoNome: 'Rettifiche e variazioni',
    regolaCentro: 'OBBLIGATORIO',
  },

  // 21 - Attrezzatura e beni strumentali minuti
  {
    code: '21.01',
    nome: 'Vetreria e attrezzatura bar',
    tipo: 'COSTO',
    mastroCode: '21',
    mastroNome: 'Attrezzatura e beni strumentali minuti',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '21.02',
    nome: 'Stoviglie, posateria e complementi sala',
    tipo: 'COSTO',
    mastroCode: '21',
    mastroNome: 'Attrezzatura e beni strumentali minuti',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '21.03',
    nome: 'Piccola attrezzatura cucina',
    tipo: 'COSTO',
    mastroCode: '21',
    mastroNome: 'Attrezzatura e beni strumentali minuti',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '21.04',
    nome: 'Beni strumentali < 516,46 EUR',
    tipo: 'COSTO',
    mastroCode: '21',
    mastroNome: 'Attrezzatura e beni strumentali minuti',
    regolaCentro: 'OBBLIGATORIO',
    nota: "Deducibili al 100% nell'esercizio",
  },
  {
    code: '21.05',
    nome: 'Arredi e complementi minuti',
    tipo: 'COSTO',
    mastroCode: '21',
    mastroNome: 'Attrezzatura e beni strumentali minuti',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '21.06',
    nome: 'Divise e abbigliamento personale',
    tipo: 'COSTO',
    mastroCode: '21',
    mastroNome: 'Attrezzatura e beni strumentali minuti',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '21.07',
    nome: 'Allestimenti, fiori e decorazioni locale',
    tipo: 'COSTO',
    mastroCode: '21',
    mastroNome: 'Attrezzatura e beni strumentali minuti',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Decorazioni ordinarie del locale (non evento)',
  },

  // 22 - Utenze
  {
    code: '22.01',
    nome: 'Energia elettrica',
    tipo: 'COSTO',
    mastroCode: '22',
    mastroNome: 'Utenze',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '22.02',
    nome: 'Gas da rete (metano)',
    tipo: 'COSTO',
    mastroCode: '22',
    mastroNome: 'Utenze',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Fornitura da impianto/contatore; di fatto solo Villa Varda',
  },
  {
    code: '22.03',
    nome: 'Acqua',
    tipo: 'COSTO',
    mastroCode: '22',
    mastroNome: 'Utenze',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '22.04',
    nome: 'Telefonia e connettività',
    tipo: 'COSTO',
    mastroCode: '22',
    mastroNome: 'Utenze',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '22.05',
    nome: 'Rifiuti - TARI e servizio smaltimento',
    tipo: 'COSTO',
    mastroCode: '22',
    mastroNome: 'Utenze',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '22.07',
    nome: 'Bombole di gas (GPL)',
    tipo: 'COSTO',
    mastroCode: '22',
    mastroNome: 'Utenze',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Acquisto ricariche; di fatto solo Casetta',
  },

  // 23 - Servizi operativi
  {
    code: '23.01',
    nome: 'Manutenzioni e riparazioni',
    tipo: 'COSTO',
    mastroCode: '23',
    mastroNome: 'Servizi operativi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '23.02',
    nome: 'Contratti di manutenzione a canone',
    tipo: 'COSTO',
    mastroCode: '23',
    mastroNome: 'Servizi operativi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '23.03',
    nome: 'Servizi di pulizia esterni',
    tipo: 'COSTO',
    mastroCode: '23',
    mastroNome: 'Servizi operativi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '23.05',
    nome: 'Vigilanza e servizi di sicurezza',
    tipo: 'COSTO',
    mastroCode: '23',
    mastroNome: 'Servizi operativi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '23.07',
    nome: 'Disinfestazione e derattizzazione',
    tipo: 'COSTO',
    mastroCode: '23',
    mastroNome: 'Servizi operativi',
    regolaCentro: 'OBBLIGATORIO',
  },

  // 24 - Servizi professionali e amministrativi
  {
    code: '24.01',
    nome: 'Consulenza contabile, fiscale e dichiarazioni',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.02',
    nome: 'Servizi elaborazione paghe',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.03',
    nome: 'Consulenze legali',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.04',
    nome: 'Consulenze tecniche e progettazione',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.05',
    nome: 'Consulenza del lavoro e sicurezza (D.Lgs. 81/08)',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.06',
    nome: 'Medico competente e sorveglianza sanitaria',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.07',
    nome: 'Formazione, HACCP e certificazioni',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.08',
    nome: 'Spese notarili e camerali',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '24.09',
    nome: 'Cancelleria e stampati',
    tipo: 'COSTO',
    mastroCode: '24',
    mastroNome: 'Servizi professionali e amministrativi',
    regolaCentro: 'DEFAULT_STR',
  },

  // 25 - Marketing e comunicazione
  {
    code: '25.01',
    nome: 'Advertising online e sponsorizzate',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '25.02',
    nome: 'Servizi fotografici e video',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '25.03',
    nome: 'Grafica e design',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '25.04',
    nome: 'Social media management',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '25.05',
    nome: 'Stampati, menu e materiale promozionale',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '25.06',
    nome: 'Sito web, domini e hosting',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '25.07',
    nome: 'Pubbliche relazioni e attività PR',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '25.08',
    nome: 'Sponsorizzazioni passive e contributi a terzi',
    tipo: 'COSTO',
    mastroCode: '25',
    mastroNome: 'Marketing e comunicazione',
    regolaCentro: 'OBBLIGATORIO',
  },

  // 26 - Costi diretti eventi
  {
    code: '26.01',
    nome: 'Artisti, DJ e compensi live',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.02',
    nome: 'Service audio-luci e noleggi tecnici',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.03',
    nome: 'Personale evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.04',
    nome: 'PR e promoter evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.05',
    nome: 'Sicurezza e steward evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.06',
    nome: 'Servizi di pulizia evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.07',
    nome: 'Advertising e sponsorizzate evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.08',
    nome: 'Foto e grafiche evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.09',
    nome: 'SIAE, SCF e diritti musicali',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.10',
    nome: 'Permessi, autorizzazioni e oneri evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '26.11',
    nome: 'Allestimenti e materiali evento',
    tipo: 'COSTO',
    mastroCode: '26',
    mastroNome: 'Costi diretti eventi',
    regolaCentro: 'OBBLIGATORIO',
  },

  // 27 - Godimento beni di terzi
  {
    code: '27.01',
    nome: 'Affitti e locazioni immobili',
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '27.02',
    nome: 'Spese condominiali',
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '27.03',
    nome: 'Canoni concessori e demaniali',
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '27.04',
    nome: 'Noleggio attrezzature',
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '27.05',
    nome: 'Noleggio automezzi',
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '27.06',
    nome: 'Canoni di leasing',
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '27.07',
    nome: 'Licenze software e canoni SaaS (POS, gestionale)',
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '27.08',
    nome: "Royalties e diritti d'uso marchio",
    tipo: 'COSTO',
    mastroCode: '27',
    mastroNome: 'Godimento beni di terzi',
    regolaCentro: 'OBBLIGATORIO',
  },

  // 28 - Costo del personale
  {
    code: '28.1.01',
    nome: 'Retribuzioni personale dipendente serale',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.02',
    nome: 'Retribuzioni personale extra e a chiamata',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.03',
    nome: 'Retribuzioni personale servizio mattina',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.04',
    nome: 'Retribuzioni personale extra mattina',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.05',
    nome: 'Retribuzioni personale pulizie',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.06',
    nome: 'Retribuzioni personale sicurezza',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.07',
    nome: 'Straordinari e maggiorazioni',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.08',
    nome: 'Ferie, permessi e mensilità aggiuntive',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.1.09',
    nome: 'Retribuzioni personale amministrativo',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.1',
    gruppoNome: 'Retribuzioni',
    regolaCentro: 'DEFAULT_STR',
    nota: "Ex voce 'Retribuzione del personale - UFFICIO'",
  },
  {
    code: '28.2.01',
    nome: 'Contributi INPS c/azienda',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.2',
    gruppoNome: 'Oneri sociali',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.2.02',
    nome: 'Contributi INAIL',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.2',
    gruppoNome: 'Oneri sociali',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.2.03',
    nome: 'Fondi integrativi ed enti bilaterali',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.2',
    gruppoNome: 'Oneri sociali',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.3.01',
    nome: 'Accantonamento TFR di competenza',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.3',
    gruppoNome: 'Accantonamenti',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.3.02',
    nome: "TFR corrisposto nell'anno",
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.3',
    gruppoNome: 'Accantonamenti',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Utilizzo del fondo: uscita finanziaria, non costo di competenza',
  },
  {
    code: '28.4.01',
    nome: 'Rimborsi spese dipendenti',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.4',
    gruppoNome: 'Altri costi del personale',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.4.02',
    nome: 'Welfare aziendale e fringe benefit',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.4',
    gruppoNome: 'Altri costi del personale',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.4.03',
    nome: 'Buoni pasto, vitto e alloggio',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.4',
    gruppoNome: 'Altri costi del personale',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.4.04',
    nome: 'Ricerca, selezione e tirocini',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.4',
    gruppoNome: 'Altri costi del personale',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '28.4.05',
    nome: 'Altri costi per personale dipendente',
    tipo: 'COSTO',
    mastroCode: '28',
    mastroNome: 'Costo del personale',
    gruppoCode: '28.4',
    gruppoNome: 'Altri costi del personale',
    regolaCentro: 'OBBLIGATORIO',
  },

  // 29 - Organi sociali e collaborazioni
  {
    code: '29.01',
    nome: 'Compenso amministratore',
    tipo: 'COSTO',
    mastroCode: '29',
    mastroNome: 'Organi sociali e collaborazioni',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '29.02',
    nome: 'Contributi INPS gestione separata amministratore',
    tipo: 'COSTO',
    mastroCode: '29',
    mastroNome: 'Organi sociali e collaborazioni',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '29.04',
    nome: 'Rimborsi spese amministratore',
    tipo: 'COSTO',
    mastroCode: '29',
    mastroNome: 'Organi sociali e collaborazioni',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '29.05',
    nome: 'Compensi per collaborazioni e prestazioni occasionali',
    tipo: 'COSTO',
    mastroCode: '29',
    mastroNome: 'Organi sociali e collaborazioni',
    regolaCentro: 'DEFAULT_STR',
  },

  // 30 - Oneri diversi di gestione
  {
    code: '30.01',
    nome: 'Imposta di bollo',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.02',
    nome: 'Tassa annuale vidimazione libri sociali',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.03',
    nome: 'Diritti camerali, catastali e vari',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.04',
    nome: 'Imposte comunali sugli immobili (IMU / ILIA)',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '30.05',
    nome: 'Occupazione suolo pubblico (COSAP / CUP)',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '30.06',
    nome: 'Abbonamenti, riviste e pubblicazioni',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.07',
    nome: 'Quote associative di categoria',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.08',
    nome: 'Assicurazioni',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '30.09',
    nome: 'Sanzioni tributarie, previdenziali e penalità',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
    nota: 'Costo indeducibile',
  },
  {
    code: '30.10',
    nome: 'Sopravvenienze passive',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.11',
    nome: 'Perdite su crediti',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.12',
    nome: 'Minusvalenze da alienazione cespiti',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.13',
    nome: 'Altri oneri di gestione',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '30.14',
    nome: "SIAE e SCF musica d'ambiente",
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'OBBLIGATORIO',
    nota: "Abbonamento annuale filodiffusione; la SIAE degli eventi resta in 26.09",
  },
  {
    code: '30.15',
    nome: 'Differenze e ammanchi di cassa',
    tipo: 'COSTO',
    mastroCode: '30',
    mastroNome: 'Oneri diversi di gestione',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Differenze tra fondo cassa teorico e contato',
  },

  // 31 - Ammortamenti e svalutazioni
  {
    code: '31.01',
    nome: 'Ammortamento immobilizzazioni immateriali',
    tipo: 'COSTO',
    mastroCode: '31',
    mastroNome: 'Ammortamenti e svalutazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '31.02',
    nome: 'Ammortamento migliorie su beni di terzi',
    tipo: 'COSTO',
    mastroCode: '31',
    mastroNome: 'Ammortamenti e svalutazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '31.03',
    nome: 'Ammortamento impianti e macchinari',
    tipo: 'COSTO',
    mastroCode: '31',
    mastroNome: 'Ammortamenti e svalutazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '31.04',
    nome: 'Ammortamento attrezzature',
    tipo: 'COSTO',
    mastroCode: '31',
    mastroNome: 'Ammortamenti e svalutazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '31.05',
    nome: 'Ammortamento mobili e arredi',
    tipo: 'COSTO',
    mastroCode: '31',
    mastroNome: 'Ammortamenti e svalutazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '31.06',
    nome: 'Ammortamento automezzi',
    tipo: 'COSTO',
    mastroCode: '31',
    mastroNome: 'Ammortamenti e svalutazioni',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '31.07',
    nome: 'Svalutazione crediti',
    tipo: 'COSTO',
    mastroCode: '31',
    mastroNome: 'Ammortamenti e svalutazioni',
    regolaCentro: 'DEFAULT_STR',
  },

  // 32 - Oneri finanziari
  {
    code: '32.1.01',
    nome: 'Interessi su mutui',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.1',
    gruppoNome: 'Interessi passivi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '32.1.02',
    nome: 'Interessi su finanziamenti e conti correnti',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.1',
    gruppoNome: 'Interessi passivi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '32.1.03',
    nome: 'Interessi di mora verso fornitori',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.1',
    gruppoNome: 'Interessi passivi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '32.1.04',
    nome: 'Interessi da ravvedimento operoso',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.1',
    gruppoNome: 'Interessi passivi',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '32.2.01',
    nome: 'Spese di tenuta conto e servizi bancari',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.2',
    gruppoNome: 'Spese e servizi bancari',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '32.2.02',
    nome: 'Commissioni su bonifici',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.2',
    gruppoNome: 'Spese e servizi bancari',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '32.2.03',
    nome: 'Commissioni RID / SDD',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.2',
    gruppoNome: 'Spese e servizi bancari',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '32.2.04',
    nome: 'Canoni POS e servizi di incasso',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.2',
    gruppoNome: 'Spese e servizi bancari',
    regolaCentro: 'OBBLIGATORIO',
    nota: 'Canone fisso terminali; le commissioni restano nel gruppo 32.3',
  },
  {
    code: '32.3.01',
    nome: 'Commissioni Pagobancomat',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.3',
    gruppoNome: 'Commissioni su incassi elettronici',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '32.3.02',
    nome: 'Commissioni carte internazionali',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.3',
    gruppoNome: 'Commissioni su incassi elettronici',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '32.3.03',
    nome: 'Commissioni SumUp',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.3',
    gruppoNome: 'Commissioni su incassi elettronici',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '32.3.04',
    nome: 'Commissioni Axerve',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.3',
    gruppoNome: 'Commissioni su incassi elettronici',
    regolaCentro: 'OBBLIGATORIO',
  },
  {
    code: '32.3.05',
    nome: 'Commissioni altri PSP e buoni pasto',
    tipo: 'COSTO',
    mastroCode: '32',
    mastroNome: 'Oneri finanziari',
    gruppoCode: '32.3',
    gruppoNome: 'Commissioni su incassi elettronici',
    regolaCentro: 'OBBLIGATORIO',
  },

  // 33 - Imposte sul reddito
  {
    code: '33.01',
    nome: 'IRES',
    tipo: 'COSTO',
    mastroCode: '33',
    mastroNome: 'Imposte sul reddito',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '33.02',
    nome: 'IRAP',
    tipo: 'COSTO',
    mastroCode: '33',
    mastroNome: 'Imposte sul reddito',
    regolaCentro: 'DEFAULT_STR',
  },
  {
    code: '33.03',
    nome: 'Imposte relative a esercizi precedenti',
    tipo: 'COSTO',
    mastroCode: '33',
    mastroNome: 'Imposte sul reddito',
    regolaCentro: 'DEFAULT_STR',
  },
]

export interface CentroDiCostoSeed {
  code: string
  name: string
  description: string
  isDefault: boolean
}

export const CENTRI_DI_COSTO: readonly CentroDiCostoSeed[] = [
  {
    code: 'STR',
    name: 'Struttura / Amministrazione',
    description:
      "Costi (e proventi) comuni non attribuibili a un locale: amministrazione, consulenze, compenso amministratore, oneri societari. Riceve i movimenti con regola 'Default STR'.",
    isDefault: true,
  },
  {
    code: 'WEISS',
    name: 'Weiss Cafè',
    description: 'Locale di Sacile: gestione ordinaria ed eventi (stagione fredda).',
    isDefault: false,
  },
  {
    code: 'VV',
    name: 'Villa Varda Bistrot',
    description: 'Bistrot Caffè Letterario a Brugnera: gestione ordinaria ed eventi del giovedì.',
    isDefault: false,
  },
  {
    code: 'CAS',
    name: 'Casetta',
    description:
      "Stand stagionale: tre weekend (gio-dom) + circa 30 aperture nel periodo natalizio. Registratore di cassa e POS propri (l'accredito su conto Weiss è solo tesoreria).",
    isDefault: false,
  },
]
